# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registered.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_reg(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(307, 454)
        self.ok = QtWidgets.QPushButton(Form)
        self.ok.setGeometry(QtCore.QRect(80, 260, 93, 28))
        self.ok.setObjectName("ok")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(20, 120, 240, 121))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.username = QtWidgets.QLabel(self.widget)
        self.username.setObjectName("username")
        self.gridLayout.addWidget(self.username, 0, 0, 1, 1)
        self.line1 = QtWidgets.QLineEdit(self.widget)
        self.line1.setObjectName("line1")
        self.gridLayout.addWidget(self.line1, 0, 1, 1, 1)
        self.password = QtWidgets.QLabel(self.widget)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 1, 0, 1, 1)
        self.line2 = QtWidgets.QLineEdit(self.widget)
        self.line2.setObjectName("line2")
        self.gridLayout.addWidget(self.line2, 1, 1, 1, 1)
        self.confirm = QtWidgets.QLabel(self.widget)
        self.confirm.setObjectName("confirm")
        self.gridLayout.addWidget(self.confirm, 2, 0, 1, 1)
        self.line3 = QtWidgets.QLineEdit(self.widget)
        self.line3.setObjectName("line3")
        self.gridLayout.addWidget(self.line3, 2, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ok.setText(_translate("Form", "注册"))
        self.username.setText(_translate("Form", "用户名"))
        self.password.setText(_translate("Form", "密码"))
        self.confirm.setText(_translate("Form", "确认密码"))
